### PR TITLE
Add Doom Emacs installation instructions

### PR DESCRIPTION
**Pull request by AlessandroW**

### CODE REVIEW

**Comment by karthink** [comment]
Thanks! Could you change "Doom" to "Doom Emacs" and move this below the manual section (and above Spacemacs)?

**Comment by M1ndo** [comment]
In *packages.el*
```elisp
(package! gptel :recipe (:host github :repo "karthink/gptel"))
```
In *bash*
```sh
doom sync
```
In *Emacs*
```elisp
M-x doom/reload-packages
M-x gptel
```

**Comment by karthink** [comment]
> In packages.el since some will experience "package not found"

I don't use Doom so I'm not sure about this -- but since gptel is on MELPA and Doom uses Straight, why would this happen?

**Comment by AlessandroW** [comment]
It won't afaik and I think it's better to pull the package from melpa than from github.

**Comment by AlessandroW** [comment]
> Thanks! Could you change "Doom" to "Doom Emacs" and move this below the manual section (and above Spacemacs)?

done

**Comment by karthink** [comment]
Cheers @AlessandroW

**Comment by M1ndo** [comment]
> > In packages.el since some will experience "package not found"
> 
> I don't use Doom so I'm not sure about this -- but since gptel is on MELPA and Doom uses Straight, why would this happen?

I honestly have no idea, i wasn't able to pull it out of melpa (other packages worked).  I just left that comment there, in-case somebody else stumbled upon the same issue.

**Pull request merged**
