### PR TITLE
Correct call to provided-mode-derived-p in gptel--strip-mode-suffix

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by karthink** [comment]
@nordlow Your change seems incorrect, `provided-mode-derived-p` takes a `&rest` argument.

```elisp
(provided-mode-derived-p MODE &rest MODES)
```

**Comment by nordlow** [comment]
Ahh, the signature has changed on master. I prefer living on the edge.

**Comment by karthink** [comment]
Per Nordlöw ***@***.***> writes:

> Ahh, the signature has changed on master. I prefer living on the edge. 

They broke all existing uses of the function?  They don't usually do that.

**Comment by karthink** [comment]
It looks like the old calling convention will continue to work but is deprecated.  Since we support Emacs back up to 27.2, the current version cannot be changed, unless `compat-30` adds the new version.  I'll add a comment about updating this in the future.

**Pull request closed without merging**
